version: '3.8'

services:
  tiko:
    build: .
    ports:
      - "9997:9997"
    volumes:
      - ./config.json:/app/config.json
      - ./tokens.json:/app/tokens.json
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - /home/pablo.cerdeira/miniconda3:/opt/miniconda3
      - /home/pablo.cerdeira/.cache/whisper:/root/.cache/whisper
    environment:
      - TZ=America/Sao_Paulo
      - PATH=/opt/miniconda3/bin:$PATH
      - PYTHONPATH=/opt/miniconda3/lib/python3.12/site-packages
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.10.10.10:9997/health?token=DevInternal92461724618920"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - local

networks:
  local:
    external: true
